language: php

php:
  - '7.1'
  - '7.1.9'
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit --bootstrap $TRAVIS_BUILD_DIR/vendor/autoload.php $TRAVIS_BUILD_DIR/tests/garbler
