language: php

php:
  - '7.1'
  - '7.1.9'
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit --bootstrap $TRAVIS_BUILD_DIR/vendor/autoload.php $TRAVIS_BUILD_DIR/tests/garbler

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
